### ISSUE TITLE
My username is constantly changing

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#117]
After logging into the website (https://neomad.org/login), access my page but my slug (and username) is incrementing always. I'm currently at 28 (https://neomad.org/@vinyll28).
Therefore I sometime see a page 404 if I refresh my profile page. I need to get to https://neomad.org/ when logged in to know what is my current username.

**Comment by Ydrasil** [comment]
Maybe #119 will fix this problem, how can I reproduce your issue ?

**Comment by fuentesloic** [comment]
@Ydrasil 
So you merged the #119, could we close this issue ?

**Comment by Ydrasil** [comment]
Yes I think we can close it @fuentesloic
