### ISSUE TITLE
I cannot open my menu in the navigation bar

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#118]
When clicking on my avatar in the top right of the website, a submenu appears:
![screen shot 2017-06-27 at 2 43 05 am](https://user-images.githubusercontent.com/145172/27566021-63afb05c-5ae2-11e7-88c7-d5d95d95fd61.png)

However it does not display on other pages.

I also have the following error except on the /around page which I suspect may be related:

```
TypeError: poisCards is null[En savoir plus]  utils.js:22:3
	window.onload https://neomad.org/static/js/utils.js:22:3
```

**Comment by fuentesloic** [comment]
@vinyll done ! directly fix on master.
For explanation: 
- onload a charge a script, avatar event listenner (on click) and some stuff for around but if we are not in around the script stop ... so I put a quick ìf` in case we are in `/around/`
