### ISSUE TITLE
Around is checking on 'around' in URL and using canvas that might not exist

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#121]
[window.onload](https://github.com/neomad-team/neomad.org/commit/ecdbb9dc147c32391637e8aaa971d21df8305225#diff-e482febebbf660e2fcb0aabdcae7bd54R18) is useless because we load the script in the end of the dom.

[detecting 'around' in URL](https://github.com/neomad-team/neomad.org/commit/ecdbb9dc147c32391637e8aaa971d21df8305225#diff-e482febebbf660e2fcb0aabdcae7bd54R20) is hackish and restrictive. What if we have a username that is called "Maround" or "aroundan". What if we use the hash '#around' or have /@loic/trips/around/ in the future? That would be tricky to debug.

If this code only involves the /around functionality, it should only be included in the _around.html_ template.

Also, what is [the canvas line](https://github.com/neomad-team/neomad.org/commit/ecdbb9dc147c32391637e8aaa971d21df8305225#diff-e482febebbf660e2fcb0aabdcae7bd54R21)?

Why do [we have a displayForm](https://github.com/neomad-team/neomad.org/commit/ecdbb9dc147c32391637e8aaa971d21df8305225#diff-e482febebbf660e2fcb0aabdcae7bd54R26) that seems not to be a form, but a collection of buttons (`….forEach(button …`)?

**Comment by fuentesloic** [comment]
PR #122
