### ISSUE TITLE
Tests are not passing

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#123]
Assigning this to the test master in chief 👑 

The tests are not passing. See: https://circleci.com/gh/neomad-team/neomad.org

> Removing tests because they're not passing is not an option 😛

**Comment by Ydrasil** [comment]
It's because _circleci_ does not find version 3.6 of python `python-build: definition not found: 3.6`
We can change it for `3.6.0` but we'll not build with the latest version of python or remove it.

**Comment by vinyll** [comment]
Good point. Which makes more sense to you @Ydrasil?
I'm ok with both :)

**Comment by Ydrasil** [comment]
@vinyll Is it important to build **neomad** now with the 3.6.x build ?

**Comment by vinyll** [comment]
Nope, that's why both solutions are ok with me.
FYI the server is currently in Python 3.5.2

**Comment by Ydrasil** [comment]
So I think that we can remove it

**Comment by Ydrasil** [comment]
We use which version of python ? We have now the same issue `python-build: definition not found: 3.5`

**Comment by vinyll** [comment]
We are using python 3.5.2 in dev and prod
