### ISSUE TITLE
features presentation in home page

### ISSUE THREAD

**Issue by fuentesloic** [neomad-team/neomad.org#129]
Let's talk about features presentation in home page, currently is :
![capture d ecran 2017-07-14 a 11 09 34](https://user-images.githubusercontent.com/8755623/28217938-f9e2da9a-6884-11e7-97c8-08d9042be8d5.png)

My purpose for this workflow, we could valide contents, after we could change design.

So our first job it's to decide wich contents are relevantest, my purpose is:

1. Read, write and contribute with nomad community
2. Share your nomad life with your own blog and map
3. Find other nomad close to you and enjoy with them
4. Find and share a place to work anywhere & anytime

Plz help meeeee :)

**Comment by vinyll** [comment]
## Read and share nomad's stories

Share the best stories that happened on your trips,
Give others your good tips for a better journey,
Whatever your level of nomadism, there are things to give and take.

   [Read from nomads]      [Write your stories]


## Track your trips

Have you ever looked where you've been and how you traveled?
Are you interested to see how your trip-mates made their journey?
Follow travelers on their map and get inspired!

   [Start sharing your trips]


## Find out what is around you

Do you know that another nomad might be in the cafe next door?
Are you looking for a good spot with WiFi where to work from?
Did you find some super spot to share with other nomads?

   [What is around you]

**Comment by fuentesloic** [comment]
First try !! @vinyll something like that:
![capture d ecran 2017-07-14 a 18 02 15-fullpage](https://user-images.githubusercontent.com/8755623/28232430-9a2d0d8e-68be-11e7-991e-2594f3800997.png)

**Comment by fuentesloic** [comment]
WIP at PR #130
