### ISSUE TITLE
Tests are unreadable due to `DeprecationWarning`

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#138]
See how https://circleci.com/gh/neomad-team/neomad.org/47#action-16 is hard to read.
We collect the `DeprecationWarning`.
Adapting the code to the recommendations should fix the readability (and make the code more persistent).

**Comment by Ydrasil** [comment]
I have some issue with the `DeprecationWarning` because `mongoengine` does not provide the function to use for avoid the `DeprecationWarning`. And the warning are in the python libraries.
I don't really know how to do :confused: 

For instance : 
```
/home/idrasil/Documents/neomad/venv/lib/python3.5/site-packages/mongoengine/document.py:339: 
DeprecationWarning: save is deprecated. Use insert_one or replace_one instead
  object_id = collection.save(doc, **write_concern)
```

**Comment by vinyll** [comment]
You may want to try to upgrade mongoengine and/or pymongo; they may have fixed that in newer version.
Because we don't have a 100% coverage, pay attention to search for all reference in our code base when changing a deprecated code. It may also exist in various places that are not run through tests.

**Comment by vinyll** [comment]
Can't do much more, warnings come from mongoengine
