### ISSUE TITLE
Homepage improvments

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#142]
When the arrow is moving, the entire contents after it are moving along:

![aug-04-2017 00-28-48](https://user-images.githubusercontent.com/145172/28946635-ebf29d9e-78ab-11e7-925b-4b1c052634bf.gif)

---

The _become a nomad_ button has an unexpected behavior:
![aug-04-2017 00-31-33](https://user-images.githubusercontent.com/145172/28946718-504b11e0-78ac-11e7-83d7-09d885f4bf63.gif)

---

The console triggers the following JS error: `TypeError: avatar is null – utils.js:36:3`

---

Buttons padding in the second section could have a larger padding, like the "Read more" from section 3.

**Comment by newick** [comment]
when you scroll (or get focus on the page, not sure) it scroll again after a delay

on the last FF version 

<img width="1437" alt="capture d ecran 2017-08-04 a 08 10 56" src="https://user-images.githubusercontent.com/657454/28958561-1c1366ac-78f7-11e7-9b84-3a6b6f9dc9f5.png">
