### ISSUE TITLE
alt in img tag

### ISSUE THREAD

**Issue by fuentesloic** [neomad-team/neomad.org#160]
There are no `alt` in `img` inside articles (we could take the title of the article?)

And if we detect a problem with an article image should we remplace it by the default one ?

**Comment by newick** [comment]
osef of alt if it's only to illustrate, we just need to have `alt=""` :)

**Comment by vinyll** [comment]
I suppose we cannot guess what the image is saying. Therefore there isn't much for filling the `alt` indeed.
We might just set it empty as suggested for the sake of compliance.
No big deal IMHO.
