### ISSUE TITLE
Homepage on dev is broken

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#164]
https://dev.neomad.org/:

- the text is moving when thw arrow is shaking.
- the _subscribe_ button has disappeared

Not sure how to deal with this and break stuff as I think you had worked on that @fuentesloic?

**Comment by fuentesloic** [comment]
@vinyll It's working for me, plz could you empty your browser cache and re try ??

**Comment by vinyll** [comment]
We still have the button that plays almost like sticky but a little strangly:
![sep-03-2017 17-15-53](https://user-images.githubusercontent.com/145172/30004222-9f2f805c-90cb-11e7-9dc2-492a7d5f01ce.gif)
