### ISSUE TITLE
Footer broken on Chrome/Chromium (for the relou)

### ISSUE THREAD

**Issue by newick** [neomad-team/neomad.org#165]
It remains in the middle of the screen on "blog" pages

<img width="1680" alt="capture d ecran 2017-08-29 a 11 07 32" src="https://user-images.githubusercontent.com/657454/29813440-601502d6-8caa-11e7-9ded-92a44bec87ab.png">

**Comment by fuentesloic** [comment]
done!! a really relou height/min-height ^^
