### ISSUE TITLE
Articles don't permit to upload video or audio

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#171]
We should be able to insert a video and/or audio into an article.

---

## Current limitation

We're currently using [Medium-Editor-Insert-Plugin 3.0](https://github.com/orthes/medium-editor-insert-plugin/tree/3.0) for inserting contents (pics and videos).

The regular (stable 2.4) version is based on JQuery.
Version 3.0 that we currently have is in VanillaJS.

It seems that this version is buggy for inserting videos.
Possible solutions are to fix the bug, or to move to the stable jquery and install jquery only for that page, or to use something else. Other options are welcome too…

**Comment by fuentesloic** [comment]
@vinyll It's also not working with image ...

**Comment by vinyll** [comment]
Mhhh… We've got to do something with the whole plugin I guess. Either replacing the editor, or the version, or just the plugin version?

But we do have images on the website that have used the current system. Did we do something that broke?

**Comment by fuentesloic** [comment]
we could use P5.js
for the image: https://p5js.org/examples/dom-drop.html
for the video: https://p5js.org/examples/dom-video.html

**Comment by vinyll** [comment]
Good idea. But how to integrate that with the [Medium Editor we are currently using](https://github.com/yabwe/medium-editor) for formatting the text or should we switch to something different?

**Comment by fuentesloic** [comment]
i found ! http://getcontenttools.com/

**Comment by vinyll** [comment]
It seems like a viable solution. We should probably remove all styling options and keep `b`, `i`, `a`, `img`, `video`. Is there `audio` btw?

**Comment by vinyll** [comment]
Some editor we could consider:

- https://quilljs.com/
- https://olivier-m.github.io/minislate/

**Comment by vinyll** [comment]
Suggestion after disussion, we permit embedding external content this way:

```
View my latest video:
embed:https://www.youtube.com/watch?v=Fa4cRMaTDUI

Listen to my favorist music:
embed:https://soundcloud.com/hamzanamira/hamza-namira-dari-ya-alby
```

That will render the following HTML:
```html
<p>View my latest video<p>
<iframe width="100%" src="https://www.youtube.com/embed/Fa4cRMaTDUI" frameborder="0" allow="encrypted-media" allowfullscreen></iframe>

<p>Listen to my favorist music:<p>
<iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/396684030&amp;color=%23ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true&amp;visual=true"></iframe>
```

**Comment by vinyll** [comment]
@marion71 
Le site en production permet maintenant d'intégrer des vidéos Youtube. Il suffit de coller l'url de la vidéo dans un paragraphe ; l'url sera remplacée par la vidéo.

**Comment by marion71** [comment]
Cool ça fonctionne ! Sauf que sur la page d'accueil, la vidéo youtube est aplatie. On veut seulement une longue bande. Quand on clique sur le lien, là oui ça fonctionne on a la vidéo en grand.




Marion Touboul
+33 6 14 73 51 98


________________________________

**Comment by marion71** [comment]
*on voit seulement




Marion Touboul
+33 6 14 73 51 98


________________________________

**Comment by vinyll** [comment]
Effecitvement, le format n’est pas encore bon.
Une chose à noter aussi, c’est https://github.com/neomad-team/neomad.org/issues/256 !!!

C’est en cours pour résoudre, mais ca démontre qu’on est sur la bonne voie ;)
