### ISSUE TITLE
Display the user trips on a map. Nicely. 

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#21]
A map currently exposes the locations where a user has traveled (when he permits his location sharing).
It looks bad right now. Let's make it look sexy 💃 

> We want to encourage a user to turn on geolocation. we should therefore make him understand what he's missing when it does not permits it or when he does not connect to Neomad.
cf: http://www.goodui.org/#24 and http://www.goodui.org/#25

**Comment by vinyll** [comment]
Suggestion: from the profile page, make a link to the user's _trips_ page.

We could put up an icon like one of these (the listed icons are authorized for reuse):
- [google map style](https://www.google.fr/search?tbs=rimg:CT73WZ9kwtC4Ijjjb2RVth1K4GXsy7owCcpiiVpsPbOS_1n94yRAK4ONrBSOzG8_1QkGzpgohRlV50LZfxydKvgI5BvSoSCeNvZFW2HUrgEYGV-Hn1KdERKhIJZezLujAJymIRabwA_1y8SRvIqEgmJWmw9s5L-fxHspwwoujJZ_1SoSCXjJEArg42sFEdYlFqHmt6juKhIJI7Mbz9CQbOkRHmUV2RLNze8qEgmCiFGVXnQtlxHKxYjgF8wzKioSCfHJ0q-AjkG9EdPeITXFuNLC,sur:fc&tbm=isch&ei=JG7bWLqZOoHZsgHjm67AAQ)
- https://pixabay.com/en/map-compass-travel-navigation-27617/
- https://pixabay.com/en/location-map-pin-pinpoint-point-162102/

**Comment by newick** [comment]
> We want to encourage a user to turn on geolocation. we should therefore make him understand what he's missing when it does not permits it or when he does not connect to Neomad.
cf: http://www.goodui.org/#24 and http://www.goodui.org/#25

@vinyll Maybe it could be great to write some text about why it's great to activate location, on a separate page ?

**Comment by fuentesloic** [comment]
feature merge on master: line between marker trip
![capture d ecran 2017-05-25 a 08 06 50](https://cloud.githubusercontent.com/assets/8755623/26449993/356d84fe-4123-11e7-9ec6-449343214a32.png)
