### ISSUE TITLE
Error 404 if you change your username and click on View my trips (profil)

### ISSUE THREAD

**Issue by Amanda-Martinez** [neomad-team/neomad.org#211]
Page : profil page
Login : yes 

## Behaviour
When you are log in on your profile page and you change your username and click on _View my trips_ link, then you arrived on a 404 error page because the link saved your preview username and not the new one. 
If you refresh the page, the username is removed and the link works. 

## Expected behaviour
The link _View my trips_ should works with the actual username without refresh the page.

**Comment by vinyll** [comment]
Basically it's more that changing your username everything containing your slug in the url will break on that page.
I'd suggest that when the username is being change, we force reload the page.

**Comment by fuentesloic** [comment]
so it's pretty a job for me right ?
