### ISSUE TITLE
The "+" icon is not completely cliquable - around me

### ISSUE THREAD

**Issue by Amanda-Martinez** [neomad-team/neomad.org#214]
Page: /around

## Behaviour

When you click on the "+" icon on the map, it's not entirely cliquable. If you click on the bottom on the +, it works but if you click above the "+" it doesn't work. 
Also, this icon is not centered.

## Expected behaviour

Ability to click on the entire icon "+" to zoom.

**Comment by fuentesloic** [comment]
done in #219
