### ISSUE TITLE
Sharing one's location is not possible on Safari iPhone

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#222]
after logging in https://neomad.org/@amber/, and clicking to share trips, the phone keeps the user logged in and redirect to the page for creating an account:

![img_4789](https://user-images.githubusercontent.com/145172/31856051-b4c05806-b67d-11e7-9504-398dd693bbaf.PNG)

**Comment by fuentesloic** [comment]
I create the *safari-fix* branch

**Comment by fuentesloic** [comment]
@vinyll Could we close this one ?

**Comment by vinyll** [comment]
Where's the branch? Did we merge and I'm just tired @fuentesloic?

**Comment by fuentesloic** [comment]
yes It's already merge

**Comment by fuentesloic** [comment]
I will try with my phone (iphone 5S) and close it if it's ok

**Comment by fuentesloic** [comment]
ok I made a mistunderstood with the problem!!! so it's really not fixed for now, I JUST fix the nav menu on mobile....

**Comment by fuentesloic** [comment]
@vinyll it's still an issue ? I think it's fix

**Comment by vinyll** [comment]
Indeed, in cannot reproduce this error on an iPhone©.
