### ISSUE TITLE
Wifi rate not displayed

### ISSUE THREAD

**Issue by newick** [neomad-team/neomad.org#225]
When I add a new point in "around" I don't see the stars to rate the Wifi.
I'm on Chrome

<img width="701" alt="capture d ecran 2017-11-06 a 15 17 57" src="https://user-images.githubusercontent.com/657454/32445415-e8c326bc-c305-11e7-8efa-1f3602750040.png">

**Comment by fuentesloic** [comment]
Could you try again with empty your "cache" ? 'cause I don't have this problem on chrome ... It's even working on safari :p

**Comment by fuentesloic** [comment]
can't re-create the bug - according the date when the issue was created I think we fix it
