### ISSUE TITLE
The new Nomads list does not display the name

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#229]
We could have the name when hovering the image, or constantly underneath, or whatever info that might be more explicit than just the pic.

<img width="862" alt="screen shot 2017-12-22 at 1 35 34 am" src="https://user-images.githubusercontent.com/145172/34280537-86f371ae-e6b8-11e7-97bc-c2d38f9b0d7e.png">

**Comment by fuentesloic** [comment]
done with PR #231
