### ISSUE TITLE
OS attribution is missing

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#232]
https://www.openstreetmap.org/copyright/en

**Comment by fuentesloic** [comment]
It's a mapbox not OSM map and we have the leaflet link for copyright. (bottom/right)

![capture d ecran 2018-02-11 a 14 34 01](https://user-images.githubusercontent.com/8755623/36077508-c1ab7b26-0f39-11e8-947f-7c2d5561a1b8.png)

**Comment by yohanboniface** [comment]
Any Mapbox map *is* an OSM based map. :)
AFAIK, the text `© OpenStreetMap contributors` must appear with a link to https://www.openstreetmap.org/copyright/en, see https://www.mapbox.com/help/how-attribution-works/ for more details when using Mapbox services.
Leaflet itself does not require any attribution.

My 2 cents :)

**Comment by fuentesloic** [comment]
@yohanboniface thx :) I'll fix it soon

**Comment by fuentesloic** [comment]
see PR https://github.com/neomad-team/neomad.org/pull/237

**Comment by vinyll** [comment]
fixed in #237
