### ISSUE TITLE
Need a reliable location service

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#241]
- User can't get localized in some circomstances, like from an iPhone sometimes.
- When connected via mobile data (and not WiFi) with GPS deactivated, the location is based on the provider and can be thousands of kilometers away (I'm constantly detected in Paris even when being in the US).

Possible solutions are to find out why it gets so inacurate, or to find another strategy.
A possible solution would be to have an empty Neomad mobile app for getting locaized.

**Comment by fuentesloic** [comment]
Could be PWA?
