### ISSUE TITLE
Hyperlink are not visible on article

### ISSUE THREAD

**Issue by marion71** [neomad-team/neomad.org#242]
It seems that the hyperlink doesn't work in in last article (draft box).

**Comment by vinyll** [comment]
Est-ce que tu peux décrire ce que tu as et ce que tu attendrais ?
C'est le lien qui est créé mais pas cliquable ? C'est le texte qui disparait ?

**Comment by marion71** [comment]
Le lien n'est pas cliquable.


________________________________
