### ISSUE TITLE
Save and publish

### ISSUE THREAD

**Issue by marion71** [neomad-team/neomad.org#244]
Il semble que cette option ne fonctionne pas. Je ne trouve rien dans les publications

**Comment by vinyll** [comment]
Est-ce toujours le cas @marion71 ou on peut fermer cette _issue_ ?

**Comment by marion71** [comment]
Ca semble toujours le cas. Quand je clique sur publish il ne se passe rien.

La police du texte aussi a changé.



________________________________

**Comment by marion71** [comment]
Pour info, dans les deux textes en "draft", la police est ok mais je ne peux pas les publier. Le bouton a disparu. J'ai seulement "edit" et quand je clique sur "edit" j'ai le texte mais pas de bouton "publish".

________________________________
