### ISSUE TITLE
Default picture on an article doesn't always make sense

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#275]
Reported from @marion71 

When writing an article, sometimes I just don't want a picture.
The current illustration makes no sense with some articles as it's not in relation at all.

**Comment by fuentesloic** [comment]
So, replace it? by what? I think a default image representing article subject / theme (related the futur tags)

**Comment by marion71** [comment]
Salut Loïc,

Il faudrait permettre le fait qu'il n'y ait parfois pas d'image du tout. Les photos ne sont pas toujours nécessaires et celle par défaut n'est pas neutre.

Je me réjouis à l'idée de publier des choses sur le blog depuis le Grand Nord !

Merci et bon dimanche,

Marion


Envoyé de mon iPhone

Le 08/04/2018 à 15:16, "Loïc" <notifications@github.com<mailto:notifications@github.com>> a écrit :


So, replace it? by what? I think a default image representing article subject / theme (related the futur tags)

**Comment by vinyll** [comment]
(depuis le **vrai** grand nord, pas le Canada aux hivers doux 🙊)

**Comment by fuentesloic** [comment]
@marion71 merci pour tes retours c’est super et très apprécié. J’en viens de corriger donc c’est fait :) manque plus que @vinyll valide

**Comment by vinyll** [comment]
Oui, c'est toujours ma faute 📦

**Comment by marion71** [comment]
Hello Loïc, Hello Vincent,


J'espère que vous allez bien. J'allais partager un post sur les réseaux sociaux et je voulais vous demander quelque chose : serait-il possible de supprimer le "by Marion Touboul" quand on partage la publication d'un post ? Je trouve que ce n'est pas nécessaire et ça fait un peu too much.


Voilà, c'est juste une suggestion.

**Comment by fuentesloic** [comment]
@marion71 hello :) 

En fait j'ai raté ton problème car tu l'as rajouté sur une issue qui pour moi était fini.
Du coup si à l'occase tu peux carrément ouvrir de nouveaux tickets (issue) pour chaque sujet ça nous arrangerai je pense.
Sur le coté droit tu peux même nous assigner dessus comme ça on pourra pas s'échapper 😁
Je te laisse essayer ? lien vers la nouvelle issue: #290

Ou alors hésite pas à me (nous) tagguer quand tu rédige un commentaire en rajoutant un @ devant notre nom et comme ça on est spécifiquement alerté.
Après on s'occupe de remettre ça comme il faut. 
Hésite pas à me demander si tu as des questions 😀 

Encore une fois merci pour tes retours!!!!

@vinyll go to #290
