### ISSUE TITLE
Enhance read time

### ISSUE THREAD

**Issue by marion71** [neomad-team/neomad.org#294]
@fuentesloic @vinyll 
il semble y avoir un bugg quand je mets une photo : le temps de lecture de l'article grimpe en flèche donc peut-être suspendre la possibilité

**Comment by fuentesloic** [comment]
@marion71 , @vinyll Je vais tenter de fixer ça ce week-end max cf #295 

EDIT: @vinyll j'ai tenté coté back mais tu connais mes compétences dans ce domaine :p 
Si tu as 5 minutes pour regarder ... j'ai fait un pauvre init mais je suis bloqué dès le modèle ...

**Comment by fuentesloic** [comment]
EDIT: issue traité et transférée sur #296

**Comment by marion71** [comment]
Bonjour Vincent, bonjour Loïc,


J'espère que vous allez bien. Serait-il possible de pouvoir modifier les dates de modif et d'ajout des articles ? Car si je veux modifier un article de mars il apparaît du coup en tout premier et c'est un peu dommage.


Merci, merci !


Marion



________________________________
