### ISSUE TITLE
Headers error in api/use/position test

### ISSUE THREAD

**Issue by fuentesloic** [neomad-team/neomad.org#310]
https://github.com/neomad-team/neomad.org/blob/090bdb1045dc9a96c6cf6c1a1a2a91c83c01c5ca/api/test.py#L44

We missed this one `Authentification` not `Authentication` ... but how it's possible to work ?

**Comment by fuentesloic** [comment]
Guess what now I know  https://github.com/neomad-team/neomad.org/blob/090bdb1045dc9a96c6cf6c1a1a2a91c83c01c5ca/api/views.py#L57

**Comment by fuentesloic** [comment]
or not ... I close it and no comments 😈  ... Shame on me 👎

**Comment by vinyll** [comment]
I don't think the word _Authentification_ exists in English, does it?
What about https://github.com/neomad-team/neomad.org/blob/090bdb1045dc9a96c6cf6c1a1a2a91c83c01c5ca/api/views.py#L57 ?
