### ISSUE TITLE
Edit custom publish date

### ISSUE THREAD

**Issue by fuentesloic** [neomad-team/neomad.org#311]
@vinyll , @marion71 - I created this new ticket because you put this issue in Enhance read time (#294) no really consisty so

from @marion71  Bonjour Vincent, bonjour Loïc,

J'espère que vous allez bien. Serait-il possible de pouvoir modifier les dates de modif et d'ajout des articles ? Car si je veux modifier un article de mars il apparaît du coup en tout premier et c'est un peu dommage.

Merci, merci !

Marion

**Comment by vinyll** [comment]
Marion utilise la réponse par mail (ca se voit puisqu'il y a une enveloppe à côté de son nom dans la réponse).
Du coup c'est un peu automatisé et elle n'a pas l'accès a créer une issue.
Merci du coup de l'avoir fait @fuentesloic ! :)

**Comment by marion71** [comment]
Oui, merci Loïck !




Marion Touboul
+33 6 14 73 51 98


________________________________

**Comment by fuentesloic** [comment]
@vinyll will be fix with the style-built-out PR (soon)
