### ISSUE TITLE
Home avatars are distorted

### ISSUE THREAD

**Issue by newick** [neomad-team/neomad.org#318]
![image](https://user-images.githubusercontent.com/657454/70393933-0aaa4d80-19f0-11ea-998a-2128e5f3b7ac.png)
`main > section img` wi

**Comment by vinyll** [comment]
Note that this does not occur on Firefox

**Comment by newick** [comment]
seems to be fixed BUT
<img width="79" alt="image" src="https://user-images.githubusercontent.com/657454/70469721-e327b380-1ac9-11ea-81be-10f4300ad1ea.png"> -> Firefox
<img width="230" alt="image" src="https://user-images.githubusercontent.com/657454/70469766-f63a8380-1ac9-11ea-9f47-1e8644ade2db.png"> -> Chromium

What is the point of `main > section img {width: 100%;}`? I don't see any effect when i remove it.

**Comment by fuentesloic** [comment]
@here will be fix with the style-built-out PR (soon)

**Comment by vinyll** [comment]
fixed in #323?
