### ISSUE TITLE
Editing an article has broken form

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#320]
<img width="616" alt="Screen Shot 2019-12-09 at 07 34 43" src="https://user-images.githubusercontent.com/145172/70412974-77583300-1a56-11ea-8a62-afdf945b9efd.png">

And the following errors appear in the console:
```
Uncaught TypeError: Cannot read property 'getAttribute' of null
    at (index):95
(index):1 Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
```

**Comment by fuentesloic** [comment]
@vinyll will be fix with the style-built-out PR (soon)

**Comment by vinyll** [comment]
fixed?

**Comment by vinyll** [comment]
This is fixed. a new ticket is being opened for fixing missing labels
