### ISSUE TITLE
We can't create create user one after another

### ISSUE THREAD

**Issue by Ydrasil** [neomad-team/neomad.org#40]
When I use make create_user one after another I have an DuplicateKeyError.
It happened because the default user name is "none"

I see several solutions here: 
- Add a field when register an user
- Instead of none, use a unique default user name or use the email for the username

**Comment by vinyll** [comment]
That's a very good point. I suffered from that too.
I would say a username is required and based on the email by default (by example based on the first part, before the _@_).
