### ISSUE TITLE
Add social account on a user profile

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#61]
Pre-establish a list of social accounts, enable editing them and display them as links on a profile page.

Display them next to the _Send an email_. Maybe the icons would be enough for these.

Twitter, Facebook, linkedIn?, Instagram

**Comment by amberfrancis** [comment]
Also have the https://twitter.com, insta.com, etc autofilled so users just need to add their username rather than type the entire URL. Also, accounts that users don't wish to fill in should be hidden from their profiles rather than just remain blank.

**Comment by fuentesloic** [comment]
@vinyll @amberfrancis done in the this [PR](https://github.com/neomad-team/neomad.org/pull/185)
