### ISSUE TITLE
The menu looks broken on mobile

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#64]
![tmp_14149-screenshot_20170417-1605361251575549](https://cloud.githubusercontent.com/assets/145172/25091378/1ecc5700-2389-11e7-9750-2b15c3d5bbc4.png)

**Comment by newick** [comment]
A solution I find interesting is in [this article](https://blog.marvelapp.com/hamburger-menu-alternatives-mobile-navigation/) 
The "more" link. We hide "Account" and "Logout" when we start getting on mobile.
Any idea @vinyll @fuentesloic ?

**Comment by vinyll** [comment]
I like the idea.
Similarly, I'd suggest to insert under the avatar anything that is user related (logout, privacy settings (coming soon), …)

A bit like:
![screen shot 2017-04-28 at 11 40 37 am](https://cloud.githubusercontent.com/assets/145172/25523596/8f0a7d22-2c07-11e7-971c-43d6c8bdb8b4.png)

**Comment by newick** [comment]
i suggest we keep the avatar for actions or link about user and if we add menu items like "Read", we could shorten them with this method as well

**Comment by vinyll** [comment]
Ok, links we have are:
- read
- around (soon)
- profile
- privacy settings (soon)
- logout

**Comment by newick** [comment]
Around (and view my trips) can be under profile part, aren't they ?

**Comment by vinyll** [comment]
- around should be visible for all users, even non registered.
- "view my trips" is also "views John Doe's trips", therefore does not seem appropriate.

I would suggest:
- read
- around
- avatar
  * my profile
  * privacy settings
  * logout

Where read and around could collapse into a "More" when screen is too small

**Comment by newick** [comment]
Proposition on "CSS" branch

**Comment by vinyll** [comment]
## Preview:

![screen shot 2017-05-02 at 9 05 31 pm](https://cloud.githubusercontent.com/assets/145172/25634484/1c69f03c-2f7b-11e7-82a9-87d07027e967.png)

👍

**Comment by vinyll** [comment]
You (@newick) were suggesting to remain coherent using _you_ or _me_ for meaning the user and seemed to prefer using _me_.
Should we then say "Around me"?

**Comment by newick** [comment]
@vinyll yup, my bad!
