### ISSUE TITLE
[around] fail localize

### ISSUE THREAD

**Issue by newick** [neomad-team/neomad.org#72]
When clicking a second time on the localize button, i go to Kenya 🙄

**Comment by vinyll** [comment]
Good place to go.
I guess that's because of the `.reverse()` that flipping the array twice.
That's a mission for @fuentesloic

**Comment by fuentesloic** [comment]
maybe you could go to Kenya ...

**Comment by vinyll** [comment]
@newick I think [this is the cheapest solution](https://www.google.fr/flights/?gl=fr#search;f=MPL;t=NBO;d=2017-05-11;r=2017-05-23;sel=MPLAMS0KL1408-AMSNBO0KQ117)

**Comment by fuentesloic** [comment]
already fixed - test prod :)
