### ISSUE TITLE
Delete its pictures when deleting an article

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#74]
When deleting an article, we should also delete its upload folder containing all its pictures

**Comment by Ydrasil** [comment]
#84 Will fix this

**Comment by fuentesloic** [comment]
I think is the same with #135

**Comment by vinyll** [comment]
They're different issues @fuentesloic.
Deleting an article now deletes the pictures on the file system ( @Ydrasil implemented that and it's merged ).
https://github.com/neomad-team/neomad.org/issues/135 is when **updating** an article that the images that have been removed from the content are not removed from the file system.

**Comment by vinyll** [comment]
However this issue has been resolved with https://github.com/neomad-team/neomad.org/pull/84
