### ISSUE TITLE
Profile photo upload orientation is rotated

### ISSUE THREAD

**Issue by amberfrancis** [neomad-team/neomad.org#75]
The photo displays upside down when uploaded from the photo album on my iPad.

**Comment by amberfrancis** [comment]
Also, the photo is distorted and does not automatically adjust resolution upon upload

**Comment by vinyll** [comment]
@amberfrancis could you share here that photo uploading upside down in order to test with it?
I haven't experiemented that.

**Comment by amberfrancis** [comment]
@vinyll i believe you can see it on my profile now https://neomad.org/@amber

**Comment by vinyll** [comment]
Indeed.
Could you attach the original picture that's not upside down so we can check what is flipping it?
(we cannot work from the rendered picture as it is upside down to us).

**Comment by amberfrancis** [comment]
![img_7649](https://cloud.githubusercontent.com/assets/27970719/25385293/97b1c444-2991-11e7-9d07-368da9eee426.JPG)

**Comment by amberfrancis** [comment]
@vinyll see the very large photo above ;)

**Comment by vinyll** [comment]
I could see [a similar report](https://github.com/orthes/medium-editor-insert-plugin/issues/453), but it seems like the picture is also upside down here.
Is it really from us or is the original picture upside down and the iPhone flipping it over somehow?
