### ISSUE TITLE
Nowhere to access account settings

### ISSUE THREAD

**Issue by amberfrancis** [neomad-team/neomad.org#76]
Can I turn on email updates? Hide my profile from the public? Change my password? Etc

**Comment by vinyll** [comment]
We don't have newsletter yet, so no email update for now ;)
Hiding from the public would mean allowing to only some users. We don't have enough users to do that yet.
Changing password, creating an account must be implemented for sure 👍

**Comment by amberfrancis** [comment]
@vinyll one still may want email updates when an important person posts a blog or checks in nearby...automated
