### ISSUE TITLE
Creating a new post 

### ISSUE THREAD

**Issue by amberfrancis** [neomad-team/neomad.org#77]
I cannot save a draft or access any saved text if I need to leave. Does the post automatically publish or save as you write? Also, the 'insert text here' text does not disappear when you start typing, requiring the user to delete it manually.

**Comment by vinyll** [comment]
Indeed. We may want a minimal width and height with a place holder to solve the delete-me-before-typing requirement.
Right now we cannot set a status like draft on an article and it's published. We should implement that drafting for sure!

**Comment by vinyll** [comment]
I'd imagine the status choice in a box attached to the bottom bar (next to the save).
We'll need to deal with multiple meta data such as _status_, eventually _publication date_, tags.
