### ISSUE TITLE
Popup on maps are away from the circle marker

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#78]
The popups position was adapted for the drop shaped marker but not anymore the the small dot.
We should reposition them.

**Comment by fuentesloic** [comment]
already fixed - test prod

**Comment by vinyll** [comment]
I see this on prod @fuentesloic 

![screen shot 2017-04-26 at 11 36 45 pm](https://cloud.githubusercontent.com/assets/145172/25458425/1f0a82a2-2ada-11e7-90ed-dca4b3a93fab.png)

**Comment by fuentesloic** [comment]
yes me too, I was wondering that's ok, you would like I stick them on the circle ? let less space ? but how many px ?
maybe the half distance ?

**Comment by vinyll** [comment]
I'd expect the same experience as with the pin:
![screen shot 2017-04-27 at 1 44 26 am](https://cloud.githubusercontent.com/assets/145172/25461758/15b5ee88-2aeb-11e7-877f-a77db2154ea2.png)

The popup pops out of the center of the circle. It looks neater, doesn't it?

**Comment by fuentesloic** [comment]
for me it's weird but now you say that I understand the movement 

> pops out of the center

I will fix it

**Comment by fuentesloic** [comment]
done in master branch 5301d52c37094599e971f4ce2f2f274ccfb8d6f5
