### ISSUE TITLE
Map dot markers are plain white on Chromium / Chrome

### ISSUE THREAD

**Issue by vinyll** [neomad-team/neomad.org#79]
the color is a hexadecimal with 8 values for transparency.
Only firefox supports that.
We should deal with transparency another way (rgba?)

**Comment by fuentesloic** [comment]
fix on master : https://github.com/neomad-team/neomad.org/commit/3b9bc338a8c24bb354fa3e95e534f24107e24a53

**Comment by newick** [comment]
maybe pushing it to prod before closing it? @vinyll @fuentesloic

**Comment by vinyll** [comment]
Pushed on prod @newick / @fuentesloic
